mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: org.garen.pitaya.mybatis.mapper
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler

spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.104.100.97:3306/pitaya?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: Garen666
      type: com.zaxxer.hikari.HikariDataSource
  redis:
      database: 0
      host: 47.104.100.97
      port: 6379
      password: Garen666
      timeout: 6000
server:
  port: 9091
  tomcat:
    max-threads: 1024
    uri-encoding: utf-8
#    basedir: /home/tomcat-cas

increment:
  path: E:\obj_store\