package org.garen.pitaya.mybatis.domain;

public class SysArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.id
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.code
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.parent_code
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.parent_name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    private String parentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.full_name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    private String fullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.full_path
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    private String fullPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.type
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.id
     *
     * @return the value of sys_area.id
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.id
     *
     * @param id the value for sys_area.id
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.code
     *
     * @return the value of sys_area.code
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.code
     *
     * @param code the value for sys_area.code
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.name
     *
     * @return the value of sys_area.name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.name
     *
     * @param name the value for sys_area.name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.parent_code
     *
     * @return the value of sys_area.parent_code
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.parent_code
     *
     * @param parentCode the value for sys_area.parent_code
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.parent_name
     *
     * @return the value of sys_area.parent_name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.parent_name
     *
     * @param parentName the value for sys_area.parent_name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.full_name
     *
     * @return the value of sys_area.full_name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.full_name
     *
     * @param fullName the value for sys_area.full_name
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.full_path
     *
     * @return the value of sys_area.full_path
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public String getFullPath() {
        return fullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.full_path
     *
     * @param fullPath the value for sys_area.full_path
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public void setFullPath(String fullPath) {
        this.fullPath = fullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.type
     *
     * @return the value of sys_area.type
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.type
     *
     * @param type the value for sys_area.type
     *
     * @mbg.generated Mon Apr 30 19:52:28 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }
}