package org.garen.pitaya.mybatis.domain;

import java.io.Serializable;

public class SysArea implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.id
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.parent_id
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.name
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.is_parent
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    private Integer isParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.fullname
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.fullpath
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    private String fullpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_area.type
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_area
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.id
     *
     * @return the value of sys_area.id
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.id
     *
     * @param id the value for sys_area.id
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.parent_id
     *
     * @return the value of sys_area.parent_id
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.parent_id
     *
     * @param parentId the value for sys_area.parent_id
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.name
     *
     * @return the value of sys_area.name
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.name
     *
     * @param name the value for sys_area.name
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.is_parent
     *
     * @return the value of sys_area.is_parent
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public Integer getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.is_parent
     *
     * @param isParent the value for sys_area.is_parent
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public void setIsParent(Integer isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.fullname
     *
     * @return the value of sys_area.fullname
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.fullname
     *
     * @param fullname the value for sys_area.fullname
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.fullpath
     *
     * @return the value of sys_area.fullpath
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public String getFullpath() {
        return fullpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.fullpath
     *
     * @param fullpath the value for sys_area.fullpath
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public void setFullpath(String fullpath) {
        this.fullpath = fullpath == null ? null : fullpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_area.type
     *
     * @return the value of sys_area.type
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_area.type
     *
     * @param type the value for sys_area.type
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SysArea other = (SysArea) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getIsParent() == null ? other.getIsParent() == null : this.getIsParent().equals(other.getIsParent()))
            && (this.getFullname() == null ? other.getFullname() == null : this.getFullname().equals(other.getFullname()))
            && (this.getFullpath() == null ? other.getFullpath() == null : this.getFullpath().equals(other.getFullpath()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_area
     *
     * @mbggenerated Thu Apr 26 18:19:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getIsParent() == null) ? 0 : getIsParent().hashCode());
        result = prime * result + ((getFullname() == null) ? 0 : getFullname().hashCode());
        result = prime * result + ((getFullpath() == null) ? 0 : getFullpath().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        return result;
    }
}