package org.garen.pitaya.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class THr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.org_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.post_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.full_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.full_path
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String fullPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.id_num
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String idNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.phone
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.emergency_contact
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String emergencyContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.emergency_contact_phone
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String emergencyContactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.email
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.marital_status
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.national
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String national;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.political
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String political;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.degree
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.native_place
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.domicile_place
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String domicilePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.work_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Date workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.entry_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Date entryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.rank_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String rankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.regular
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Boolean regular;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.regular_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Date regularDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.work_age
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Double workAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.work_status
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String workStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.available
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.create_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hr.update_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_hr
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.code
     *
     * @return the value of t_hr.code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.code
     *
     * @param code the value for t_hr.code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.name
     *
     * @return the value of t_hr.name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.name
     *
     * @param name the value for t_hr.name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.org_code
     *
     * @return the value of t_hr.org_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.org_code
     *
     * @param orgCode the value for t_hr.org_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.post_code
     *
     * @return the value of t_hr.post_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.post_code
     *
     * @param postCode the value for t_hr.post_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.full_name
     *
     * @return the value of t_hr.full_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.full_name
     *
     * @param fullName the value for t_hr.full_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.full_path
     *
     * @return the value of t_hr.full_path
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getFullPath() {
        return fullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.full_path
     *
     * @param fullPath the value for t_hr.full_path
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setFullPath(String fullPath) {
        this.fullPath = fullPath == null ? null : fullPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.id_num
     *
     * @return the value of t_hr.id_num
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.id_num
     *
     * @param idNum the value for t_hr.id_num
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.phone
     *
     * @return the value of t_hr.phone
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.phone
     *
     * @param phone the value for t_hr.phone
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.emergency_contact
     *
     * @return the value of t_hr.emergency_contact
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getEmergencyContact() {
        return emergencyContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.emergency_contact
     *
     * @param emergencyContact the value for t_hr.emergency_contact
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setEmergencyContact(String emergencyContact) {
        this.emergencyContact = emergencyContact == null ? null : emergencyContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.emergency_contact_phone
     *
     * @return the value of t_hr.emergency_contact_phone
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getEmergencyContactPhone() {
        return emergencyContactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.emergency_contact_phone
     *
     * @param emergencyContactPhone the value for t_hr.emergency_contact_phone
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setEmergencyContactPhone(String emergencyContactPhone) {
        this.emergencyContactPhone = emergencyContactPhone == null ? null : emergencyContactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.email
     *
     * @return the value of t_hr.email
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.email
     *
     * @param email the value for t_hr.email
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.marital_status
     *
     * @return the value of t_hr.marital_status
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.marital_status
     *
     * @param maritalStatus the value for t_hr.marital_status
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.national
     *
     * @return the value of t_hr.national
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getNational() {
        return national;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.national
     *
     * @param national the value for t_hr.national
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setNational(String national) {
        this.national = national == null ? null : national.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.political
     *
     * @return the value of t_hr.political
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getPolitical() {
        return political;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.political
     *
     * @param political the value for t_hr.political
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setPolitical(String political) {
        this.political = political == null ? null : political.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.degree
     *
     * @return the value of t_hr.degree
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.degree
     *
     * @param degree the value for t_hr.degree
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.native_place
     *
     * @return the value of t_hr.native_place
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.native_place
     *
     * @param nativePlace the value for t_hr.native_place
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace == null ? null : nativePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.domicile_place
     *
     * @return the value of t_hr.domicile_place
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getDomicilePlace() {
        return domicilePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.domicile_place
     *
     * @param domicilePlace the value for t_hr.domicile_place
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setDomicilePlace(String domicilePlace) {
        this.domicilePlace = domicilePlace == null ? null : domicilePlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.work_date
     *
     * @return the value of t_hr.work_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Date getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.work_date
     *
     * @param workDate the value for t_hr.work_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setWorkDate(Date workDate) {
        this.workDate = workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.entry_date
     *
     * @return the value of t_hr.entry_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.entry_date
     *
     * @param entryDate the value for t_hr.entry_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.rank_name
     *
     * @return the value of t_hr.rank_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getRankName() {
        return rankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.rank_name
     *
     * @param rankName the value for t_hr.rank_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setRankName(String rankName) {
        this.rankName = rankName == null ? null : rankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.regular
     *
     * @return the value of t_hr.regular
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Boolean getRegular() {
        return regular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.regular
     *
     * @param regular the value for t_hr.regular
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setRegular(Boolean regular) {
        this.regular = regular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.regular_date
     *
     * @return the value of t_hr.regular_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Date getRegularDate() {
        return regularDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.regular_date
     *
     * @param regularDate the value for t_hr.regular_date
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setRegularDate(Date regularDate) {
        this.regularDate = regularDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.work_age
     *
     * @return the value of t_hr.work_age
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Double getWorkAge() {
        return workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.work_age
     *
     * @param workAge the value for t_hr.work_age
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setWorkAge(Double workAge) {
        this.workAge = workAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.work_status
     *
     * @return the value of t_hr.work_status
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getWorkStatus() {
        return workStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.work_status
     *
     * @param workStatus the value for t_hr.work_status
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setWorkStatus(String workStatus) {
        this.workStatus = workStatus == null ? null : workStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.available
     *
     * @return the value of t_hr.available
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.available
     *
     * @param available the value for t_hr.available
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.create_time
     *
     * @return the value of t_hr.create_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.create_time
     *
     * @param createTime the value for t_hr.create_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hr.update_time
     *
     * @return the value of t_hr.update_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hr.update_time
     *
     * @param updateTime the value for t_hr.update_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hr
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        THr other = (THr) that;
        return (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getPostCode() == null ? other.getPostCode() == null : this.getPostCode().equals(other.getPostCode()))
            && (this.getFullName() == null ? other.getFullName() == null : this.getFullName().equals(other.getFullName()))
            && (this.getFullPath() == null ? other.getFullPath() == null : this.getFullPath().equals(other.getFullPath()))
            && (this.getIdNum() == null ? other.getIdNum() == null : this.getIdNum().equals(other.getIdNum()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getEmergencyContact() == null ? other.getEmergencyContact() == null : this.getEmergencyContact().equals(other.getEmergencyContact()))
            && (this.getEmergencyContactPhone() == null ? other.getEmergencyContactPhone() == null : this.getEmergencyContactPhone().equals(other.getEmergencyContactPhone()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMaritalStatus() == null ? other.getMaritalStatus() == null : this.getMaritalStatus().equals(other.getMaritalStatus()))
            && (this.getNational() == null ? other.getNational() == null : this.getNational().equals(other.getNational()))
            && (this.getPolitical() == null ? other.getPolitical() == null : this.getPolitical().equals(other.getPolitical()))
            && (this.getDegree() == null ? other.getDegree() == null : this.getDegree().equals(other.getDegree()))
            && (this.getNativePlace() == null ? other.getNativePlace() == null : this.getNativePlace().equals(other.getNativePlace()))
            && (this.getDomicilePlace() == null ? other.getDomicilePlace() == null : this.getDomicilePlace().equals(other.getDomicilePlace()))
            && (this.getWorkDate() == null ? other.getWorkDate() == null : this.getWorkDate().equals(other.getWorkDate()))
            && (this.getEntryDate() == null ? other.getEntryDate() == null : this.getEntryDate().equals(other.getEntryDate()))
            && (this.getRankName() == null ? other.getRankName() == null : this.getRankName().equals(other.getRankName()))
            && (this.getRegular() == null ? other.getRegular() == null : this.getRegular().equals(other.getRegular()))
            && (this.getRegularDate() == null ? other.getRegularDate() == null : this.getRegularDate().equals(other.getRegularDate()))
            && (this.getWorkAge() == null ? other.getWorkAge() == null : this.getWorkAge().equals(other.getWorkAge()))
            && (this.getWorkStatus() == null ? other.getWorkStatus() == null : this.getWorkStatus().equals(other.getWorkStatus()))
            && (this.getAvailable() == null ? other.getAvailable() == null : this.getAvailable().equals(other.getAvailable()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hr
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getPostCode() == null) ? 0 : getPostCode().hashCode());
        result = prime * result + ((getFullName() == null) ? 0 : getFullName().hashCode());
        result = prime * result + ((getFullPath() == null) ? 0 : getFullPath().hashCode());
        result = prime * result + ((getIdNum() == null) ? 0 : getIdNum().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getEmergencyContact() == null) ? 0 : getEmergencyContact().hashCode());
        result = prime * result + ((getEmergencyContactPhone() == null) ? 0 : getEmergencyContactPhone().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMaritalStatus() == null) ? 0 : getMaritalStatus().hashCode());
        result = prime * result + ((getNational() == null) ? 0 : getNational().hashCode());
        result = prime * result + ((getPolitical() == null) ? 0 : getPolitical().hashCode());
        result = prime * result + ((getDegree() == null) ? 0 : getDegree().hashCode());
        result = prime * result + ((getNativePlace() == null) ? 0 : getNativePlace().hashCode());
        result = prime * result + ((getDomicilePlace() == null) ? 0 : getDomicilePlace().hashCode());
        result = prime * result + ((getWorkDate() == null) ? 0 : getWorkDate().hashCode());
        result = prime * result + ((getEntryDate() == null) ? 0 : getEntryDate().hashCode());
        result = prime * result + ((getRankName() == null) ? 0 : getRankName().hashCode());
        result = prime * result + ((getRegular() == null) ? 0 : getRegular().hashCode());
        result = prime * result + ((getRegularDate() == null) ? 0 : getRegularDate().hashCode());
        result = prime * result + ((getWorkAge() == null) ? 0 : getWorkAge().hashCode());
        result = prime * result + ((getWorkStatus() == null) ? 0 : getWorkStatus().hashCode());
        result = prime * result + ((getAvailable() == null) ? 0 : getAvailable().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}