package org.garen.pitaya.mybatis.domain;

import java.io.Serializable;
import java.util.Date;

public class TPost implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.org_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.full_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.full_path
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private String fullPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.available
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Boolean available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.level
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.create_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_post.update_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_post
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.code
     *
     * @return the value of t_post.code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.code
     *
     * @param code the value for t_post.code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.name
     *
     * @return the value of t_post.name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.name
     *
     * @param name the value for t_post.name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.org_code
     *
     * @return the value of t_post.org_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.org_code
     *
     * @param orgCode the value for t_post.org_code
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.full_name
     *
     * @return the value of t_post.full_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.full_name
     *
     * @param fullName the value for t_post.full_name
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.full_path
     *
     * @return the value of t_post.full_path
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public String getFullPath() {
        return fullPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.full_path
     *
     * @param fullPath the value for t_post.full_path
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setFullPath(String fullPath) {
        this.fullPath = fullPath == null ? null : fullPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.available
     *
     * @return the value of t_post.available
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.available
     *
     * @param available the value for t_post.available
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.level
     *
     * @return the value of t_post.level
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.level
     *
     * @param level the value for t_post.level
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.create_time
     *
     * @return the value of t_post.create_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.create_time
     *
     * @param createTime the value for t_post.create_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_post.update_time
     *
     * @return the value of t_post.update_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_post.update_time
     *
     * @param updateTime the value for t_post.update_time
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TPost other = (TPost) that;
        return (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getOrgCode() == null ? other.getOrgCode() == null : this.getOrgCode().equals(other.getOrgCode()))
            && (this.getFullName() == null ? other.getFullName() == null : this.getFullName().equals(other.getFullName()))
            && (this.getFullPath() == null ? other.getFullPath() == null : this.getFullPath().equals(other.getFullPath()))
            && (this.getAvailable() == null ? other.getAvailable() == null : this.getAvailable().equals(other.getAvailable()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_post
     *
     * @mbggenerated Thu May 31 14:20:28 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOrgCode() == null) ? 0 : getOrgCode().hashCode());
        result = prime * result + ((getFullName() == null) ? 0 : getFullName().hashCode());
        result = prime * result + ((getFullPath() == null) ? 0 : getFullPath().hashCode());
        result = prime * result + ((getAvailable() == null) ? 0 : getAvailable().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}